export const UserSeedData = [
  {
    email: "admin@gmail.com",
    password: "$argon2id$v=19$m=19456,t=2,p=1$RTlnxzJ7OVcRp/wdwlTzBA$1sUwI0r/di7u1pFEta4qrkhkpYEW6JUN+a/ZHn93SXo",
    id: "4d942489-fffb-4272-ae1a-af670ff50e76",
    role: "admin",
  },
  {
    email: "user@gmail.com",
    password: "$argon2id$v=19$m=19456,t=2,p=1$RTlnxzJ7OVcRp/wdwlTzBA$1sUwI0r/di7u1pFEta4qrkhkpYEW6JUN+a/ZHn93SXo",
    id: "4d942489-fffb-4272-ae1a-af670ff50e75",
    role: "user",
  },
  {
    email: "guest@gmail.com",
    password: "$argon2id$v=19$m=19456,t=2,p=1$RTlnxzJ7OVcRp/wdwlTzBA$1sUwI0r/di7u1pFEta4qrkhkpYEW6JUN+a/ZHn93SXo",
    id: "4d942489-fffb-4272-ae1a-af670ff50e74",
    role: "user",
  },
]

export const BookSeedData = [
  {
    code: "CALC-101",
    title: "Calculus: Early Transcendentals",
    description: "Comprehensive calculus textbook covering derivatives, integrals, and advanced mathematical concepts",
    publicationYear: 2020,
    condition: "Excellent",
    cover_photo: "uploads/unsplash.jpg",
    price: 750000,
    grade: "Advanced",
    writer: "James Stewart",
    class: "Perguruan Tinggi",
    category: "Matematika",
    publisher: "Cengage Learning",
    rack: "Perguruan Tinggi",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "DINO-KID",
    title: "Petualangan Dinosaurus Kecil",
    description: "Buku cerita bergambar tentang persahabatan dinosaurus untuk anak-anak",
    publicationYear: 2023,
    condition: "New",
    cover_photo: "uploads/unsplash.jpg",
    price: 125000,
    grade: "Elementary",
    writer: "Sarah Johnson",
    class: "Anak-anak",
    category: "Cerita Bergambar",
    publisher: "Gramedia Kids",
    rack: "Anak-anak",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "PHY-201",
    title: "Fundamentals of Physics",
    description: "Comprehensive physics textbook for undergraduate students",
    publicationYear: 2021,
    condition: "Good",
    cover_photo: "uploads/unsplash.jpg",
    price: 680000,
    grade: "University",
    writer: "David Halliday",
    class: "Perguruan Tinggi",
    category: "Fisika",
    publisher: "Wiley",
    rack: "Perguruan Tinggi",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "ABC-123",
    title: "Belajar Membaca Bersama",
    description: "Buku latihan membaca untuk anak usia dini",
    publicationYear: 2024,
    condition: "New",
    cover_photo: "uploads/unsplash.jpg",
    price: 95000,
    grade: "Preschool",
    writer: "Maria Susanti",
    class: "Anak-anak",
    category: "Pendidikan",
    publisher: "Erlangga Kids",
    rack: "Anak-anak",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "CHEM-301",
    title: "Organic Chemistry",
    description: "Advanced organic chemistry textbook for chemistry majors",
    publicationYear: 2022,
    condition: "Excellent",
    cover_photo: "uploads/unsplash.jpg",
    price: 850000,
    grade: "Advanced",
    writer: "John McMurry",
    class: "Perguruan Tinggi",
    category: "Kimia",
    publisher: "Pearson",
    rack: "Perguruan Tinggi",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "FAIRY-01",
    title: "Kumpulan Dongeng Nusantara",
    description: "Koleksi cerita rakyat dari berbagai daerah di Indonesia",
    publicationYear: 2023,
    condition: "New",
    cover_photo: "uploads/unsplash.jpg",
    price: 150000,
    grade: "Elementary",
    writer: "Tim Penulis Nusantara",
    class: "Anak-anak",
    category: "Dongeng",
    publisher: "Balai Pustaka",
    rack: "Anak-anak",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "ECON-201",
    title: "Principles of Microeconomics",
    description: "Fundamental concepts of microeconomics for undergraduate students",
    publicationYear: 2021,
    condition: "Good",
    cover_photo: "uploads/unsplash.jpg",
    price: 550000,
    grade: "University",
    writer: "N. Gregory Mankiw",
    class: "Perguruan Tinggi",
    category: "Ekonomi",
    publisher: "Cengage Learning",
    rack: "Perguruan Tinggi",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "MATH-KID",
    title: "Matematika Menyenangkan",
    description: "Buku latihan matematika dengan ilustrasi menarik untuk anak-anak",
    publicationYear: 2024,
    condition: "New",
    cover_photo: "uploads/unsplash.jpg",
    price: 110000,
    grade: "Elementary",
    writer: "Budi Santoso",
    class: "Anak-anak",
    category: "Pendidikan",
    publisher: "Gramedia Kids",
    rack: "Anak-anak",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "BIO-101",
    title: "Essential Cell Biology",
    description: "Comprehensive introduction to cell biology for undergraduate students",
    publicationYear: 2022,
    condition: "Excellent",
    cover_photo: "uploads/unsplash.jpg",
    price: 720000,
    grade: "University",
    writer: "Bruce Alberts",
    class: "Perguruan Tinggi",
    category: "Biologi",
    publisher: "Norton",
    rack: "Perguruan Tinggi",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "STORY-02",
    title: "Petualangan di Taman Safari",
    description: "Cerita petualangan anak-anak mengunjungi kebun binatang",
    publicationYear: 2023,
    condition: "New",
    cover_photo: "uploads/unsplash.jpg",
    price: 135000,
    grade: "Elementary",
    writer: "Linda Wijaya",
    class: "Anak-anak",
    category: "Cerita Bergambar",
    publisher: "Erlangga Kids",
    rack: "Anak-anak",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "PSYCH-201",
    title: "Introduction to Psychology",
    description: "Fundamental concepts of modern psychology for undergraduate students",
    publicationYear: 2023,
    condition: "Excellent",
    cover_photo: "uploads/unsplash.jpg",
    price: 645000,
    grade: "University",
    writer: "David Myers",
    class: "Perguruan Tinggi",
    category: "Psikologi",
    publisher: "Worth Publishers",
    rack: "Perguruan Tinggi",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "KIDS-ABC",
    title: "Mengenal Alfabet dengan Lagu",
    description: "Buku interaktif belajar alfabet dengan lagu-lagu menarik",
    publicationYear: 2024,
    condition: "New",
    cover_photo: "uploads/unsplash.jpg",
    price: 115000,
    grade: "Preschool",
    writer: "Rina Putri",
    class: "Anak-anak",
    category: "Pendidikan",
    publisher: "Gramedia Kids",
    rack: "Anak-anak",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "COMP-301",
    title: "Data Structures and Algorithms",
    description: "Advanced computer science concepts for programming students",
    publicationYear: 2022,
    condition: "Good",
    cover_photo: "uploads/unsplash.jpg",
    price: 580000,
    grade: "University",
    writer: "Robert Sedgewick",
    class: "Perguruan Tinggi",
    category: "Informatika",
    publisher: "Addison-Wesley",
    rack: "Perguruan Tinggi",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "ANIMAL-FUN",
    title: "Mengenal Hewan-Hewan Lucu",
    description: "Buku bergambar tentang berbagai hewan dengan fakta menarik",
    publicationYear: 2023,
    condition: "New",
    cover_photo: "uploads/unsplash.jpg",
    price: 98000,
    grade: "Elementary",
    writer: "Ani Suryani",
    class: "Anak-anak",
    category: "Cerita Bergambar",
    publisher: "Erlangga Kids",
    rack: "Anak-anak",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "ENG-401",
    title: "Advanced English Literature",
    description: "Analysis of classical and modern literature for advanced students",
    publicationYear: 2021,
    condition: "Good",
    cover_photo: "uploads/unsplash.jpg",
    price: 490000,
    grade: "University",
    writer: "Michael Wood",
    class: "Perguruan Tinggi",
    category: "Sastra",
    publisher: "Oxford Press",
    rack: "Perguruan Tinggi",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "KIDS-COOK",
    title: "Mari Belajar Memasak",
    description: "Buku resep sederhana untuk anak-anak dengan ilustrasi menarik",
    publicationYear: 2024,
    condition: "New",
    cover_photo: "uploads/unsplash.jpg",
    price: 125000,
    grade: "Elementary",
    writer: "Chef Junior Indonesia",
    class: "Anak-anak",
    category: "Aktivitas",
    publisher: "Gramedia Kids",
    rack: "Anak-anak",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "ARCH-201",
    title: "Principles of Architecture",
    description: "Fundamental concepts of architectural design and theory",
    publicationYear: 2022,
    condition: "Excellent",
    cover_photo: "uploads/unsplash.jpg",
    price: 875000,
    grade: "University",
    writer: "Francis D.K. Ching",
    class: "Perguruan Tinggi",
    category: "Arsitektur",
    publisher: "Wiley",
    rack: "Perguruan Tinggi",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "FAIRY-02",
    title: "Kisah Putri dan Peri",
    description: "Kumpulan dongeng tentang putri dan peri ajaib",
    publicationYear: 2023,
    condition: "New",
    cover_photo: "uploads/unsplash.jpg",
    price: 145000,
    grade: "Elementary",
    writer: "Diana Putri",
    class: "Anak-anak",
    category: "Dongeng",
    publisher: "Balai Pustaka",
    rack: "Anak-anak",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "MED-301",
    title: "Human Anatomy and Physiology",
    description: "Comprehensive study of human body systems for medical students",
    publicationYear: 2023,
    condition: "Excellent",
    cover_photo: "uploads/unsplash.jpg",
    price: 950000,
    grade: "University",
    writer: "Elaine Marieb",
    class: "Perguruan Tinggi",
    category: "Kedokteran",
    publisher: "Pearson",
    rack: "Perguruan Tinggi",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  },
  {
    code: "CRAFT-KID",
    title: "Kreasi Tangan Cilik",
    description: "Panduan membuat kerajinan tangan sederhana untuk anak-anak",
    publicationYear: 2024,
    condition: "New",
    cover_photo: "uploads/unsplash.jpg",
    price: 135000,
    grade: "Elementary",
    writer: "Tim Kreatif Anak",
    class: "Anak-anak",
    category: "Aktivitas",
    publisher: "Erlangga Kids",
    rack: "Anak-anak",
    created_by: "4d942489-fffb-4272-ae1a-af670ff50e76"
  }
]

export const BorrowingSeedData = [
  {
    userId: "4d942489-fffb-4272-ae1a-af670ff50e75",
    bookCode: "CALC-101",
    returned_date: null,
    status: "BORROWED",
    fine_amount: 0,
    created_by: "admin"
  },
  {
    userId: "4d942489-fffb-4272-ae1a-af670ff50e74",
    bookCode: "DINO-KID",
    returned_date: null,
    status: "RETURNED",
    fine_amount: 0,
    created_by: "self"
  },
  {
    userId: "4d942489-fffb-4272-ae1a-af670ff50e76",
    bookCode: "PHY-201",
    returned_date: null,
    status: "BORROWED",
    fine_amount: 0,
    created_by: "admin"
  },
  {
    userId: "4d942489-fffb-4272-ae1a-af670ff50e75",
    bookCode: "ABC-123",
    returned_date: null,
    status: "RETURNED",
    fine_amount: 0,
    created_by: "self"
  },
  {
    userId: "4d942489-fffb-4272-ae1a-af670ff50e74",
    bookCode: "CHEM-301",
    returned_date: null,
    status: "BORROWED",
    fine_amount: 0,
    created_by: "admin"
  },
  {
    userId: "4d942489-fffb-4272-ae1a-af670ff50e76",
    bookCode: "FAIRY-01",
    returned_date: null,
    status: "BORROWED",
    fine_amount: 0,
    created_by: "self"
  },
  {
    userId: "4d942489-fffb-4272-ae1a-af670ff50e75",
    bookCode: "ECON-201",
    returned_date: null,
    status: "BORROWED",
    fine_amount: 0,
    created_by: "admin"
  },
  {
    userId: "4d942489-fffb-4272-ae1a-af670ff50e74",
    bookCode: "MATH-KID",
    returned_date: null,
    status: "BORROWED",
    fine_amount: 0,
    created_by: "self"
  },
  {
    userId: "4d942489-fffb-4272-ae1a-af670ff50e76",
    bookCode: "BIO-101",
    returned_date: null,
    status: "BORROWED",
    fine_amount: 0,
    created_by: "admin"
  },
  {
    userId: "4d942489-fffb-4272-ae1a-af670ff50e75",
    bookCode: "STORY-02",
    returned_date: null,
    status: "BORROWED",
    fine_amount: 0,
    created_by: "self"
  }
]