name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Load environment
            source ~/.bashrc
            source ~/.profile
            export PATH="$HOME/.nvm/versions/node/v22.13.1/bin:$HOME/.local/share/pnpm:$PATH"

            # Debugging check
            which git || echo "git not found"
            which bun || echo "bun not found"
            which pm2 || echo "pm2 not found"

            cd ~/app/librarian
            git pull origin main
            git status

            export DATABASE_URL="${{ secrets.DATABASE_URL }}"
            export APP_NAME="${{ secrets.APP_NAME }}"
            export SECRET_SESSION_KEY="${{ secrets.SECRET_SESSION_KEY }}"
            export PORT="${{ secrets.PORT }}"

            # Debugging env
            printenv | grep DATABASE_URL || echo "DATABASE_URL not found"
            printenv | grep APP_NAME || echo "APP_NAME not found"

            bun install
            bun generate
            bun migrate

            pm2 reload librarian
            pm2 restart librarian
