name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-20.04.3

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/app/librarian
            git pull origin main
            git status
            pnpm install
            pnpm build
            pm2 reload librarian
            pm2 restart librarian
